### ISSUE TITLE
New Header fetching on windows

### ISSUE THREAD

**Issue by steffengy** [cznic/sqlite2go#5]
From my point of view the new header fetching doesn't do what it's supposed to.
It picks up windows.h, but not all .h files that it depends on (which are quite a few hundred).

(c99/headers)

Anything I should know about these changes/how it's supposed to work?

**Comment by cznic** [comment]
Maybe try to add a debug print of `s` here: https://github.com/cznic/sqlite2go/blob/6dd489657fe397cd4829b47d25318a677e242c0e/internal/c99/headers/generator.go#L135. It should show all included files, recursively.

**Comment by steffengy** [comment]
Seems to be a very long ifdef I missed, so probably all good.
