### ISSUE TITLE
anonymous union access broken again?

### ISSUE THREAD

**Issue by steffengy** [cznic/sqlite2go#6]
Seems like we got that broken again, i remeber we should have a test in place for that?
https://github.com/cznic/sqlite2go/blob/6f364c284b320320564d686887eec89740cb1bd4/internal/c99/testdata/bug/13.c

sqlite2go: PANIC: D:\projects\Go\gopath\src\github.com\cznic\sqlite2go\_sqlite\sqlite-amalgamation-3210000\sqlite3.c:40754:5
github.com/cznic/sqlite2go/internal/c99.(*Expr).eval(0xc046933ce0, 0xc042216000, 0xc046933e01, 0xc0468d2b60, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/projects/Go/gopath/src/github.com/cznic/sqlite2go/internal/c99/ast2.go:753 +0xf6d3
github.com/cznic/sqlite2go/internal/c99.(*Expr).eval(0xc046933ea0, 0xc042216000, 0x1, 0xc0468d2b60, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/projects/Go/gopath/src/github.com/cznic/sqlite2go/internal/c99/ast2.go:1131 +0xaf00
github.com/cznic/sqlite2go/internal/c99.(*ExprList).eval(0xc0442822d0, 0xc042216000, 0xc04c90aa01, 0xc0468d2b60, 0x0, 0x0, 0x0, 0x0, 0x0)

**Comment by cznic** [comment]
FTR on linux_amd64

```
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/ccgo> git branch 
* master
  ok
  wips
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/ccgo> git --no-pager log -1
commit 6dd489657fe397cd4829b47d25318a677e242c0e (HEAD -> master, origin/master, origin/HEAD, ok)
Author: Jan Mercl <0xjnml@gmail.com>
Date:   Fri Apr 27 16:36:15 2018 +0200

    Overhaul waitpid patch.
    
            modified:   all_test.go
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/ccgo> go test -v -run Other -trc
=== RUN   TestOther
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/1.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/10.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/11.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/12.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/13.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/14.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/15.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/16.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/17.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/18.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/19.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/2.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/3.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/4.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/5.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/6.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/7.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/8.c]
[/home/jnml/src/github.com/cznic/sqlite2go/internal/c99/headers/linux_amd64/builtin.h ../c99/testdata/bug/9.c]
--- PASS: TestOther (4.72s)
PASS
ok  	github.com/cznic/sqlite2go/internal/ccgo	4.726s
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/ccgo> 
```

**Comment by steffengy** [comment]
Yep, was another missing define, since this lot is really a soup of hacks.

**Comment by cznic** [comment]
> Yep, was another missing define, since this lot is really a soup of hacks.

I'm curious, what kind of hacks? Nowadays there should not be many of them, hopefully, as we'are using the system headers unmodified, even though copied for easy cross compilation/translation.

I'd have hoped that the proper `#define` set is mostly captured by `generator.go` in c99/headers. Or the issue is with SQLite's own defines?

**Comment by cznic** [comment]
OMG, I think I understand now. Is there anything I can help you with? (Except for knowing anything about Windows)

**Comment by steffengy** [comment]
@cznic
How are the folders in cznic/crt generated? 
Or are they jsut outdated and can be removed?
Also can sqlite3shell/internal/crt be removed or is it still used by x86-linux?
